sudo: required
services:
  - docker

before_install:
  - docker build -t jessemellinger/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jessemellinger/react-test npm test -- --coverage

after_success:
  - docker build -t jessemellinger/multi-client ./client
  - docker build -t jessemellinger/multi-nginx ./nginx
  - docker build -t jessemellinger/multi-server ./server
  - docker build -t jessemellinger/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jessmellinger/multi-client
  - docker push jessemellinger/multi-nginx
  - docker push jessemellinger/multi-server
  - docker push jessemellinger/multi-worker